### ISSUE TITLE
Transactions loading stuck

### ISSUE THREAD

**Issue by koen20** [apemanzilla/KWallet#1]
Transactions isn't working. After 20 minutes it is still loading.
![kwallet](https://cloud.githubusercontent.com/assets/6172623/6578730/24a22994-c746-11e4-953c-ccc6c59ef01a.PNG)

**Comment by dmarcuse** [comment]
Are there any exceptions if you run it from command line?

**Comment by koen20** [comment]
If i run it with java -jar KWallet.jar
![capture](https://cloud.githubusercontent.com/assets/6172623/6582810/2005fbc6-c760-11e4-9742-58bae3f999a4.PNG)

**Comment by dmarcuse** [comment]
This is an odd bug, and I can't seem to reproduce it (Windows 7 x64, tried JRE 8 and JDK 7 u67). It should be working perfectly fine.

From all my tests, I can load your transaction data fine.

**Comment by koen20** [comment]
I am using windows 8.1 x64
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

**Comment by dmarcuse** [comment]
Could you try running it with Java 7?

**Comment by dmarcuse** [comment]
Fixed as of e5577a24f7cfad0cf76c26c91b8834ac2c0f128a
